PrimerNivel = ['XXXXXXXXXXXXXXXX',
               'X XXXXXXX  XXX X',
               'X XXX XX  XXX  X',
               'X        XX   XX',
               'XXXXXX      XXXX',
               'X      XX     XX',
               'X XXXXXXXXXXX  X',
               'X      X       X',
               'XXX    X    XXXX',
               'XXXXXXXXXXXXXXXX']
SegundoNivel = ['XXXXXXXXXXXXXXXX',
               'X      XXXXXX   X',
               'XXXXXX XXXXXXX  X',
               'XXXXXX          X',
               'X      XXXXXXX  X',
               'X XXXX XXXXXXXX X',
               'X  XX        XX X',
               'X  XX  XXX  XXXXX',
               'X  XX  XXXX XXXXX',
               'XXXXXXXXXXXXXXXX']
TercerNivel = ['XXXXXXXXXXXXXXXX',
               'X           XXXX',
               'XXX XXXX  X XXXX',
               'XXX XXXX  X  XXX',
               'XXXXXXXX  X  XXX',
               'XXXXXXXX  XXXXXX',
               'X              X',
               'X              X',
               'X              X',
               'XXXXXXXXXXXXXXXX']

