''' Descripcion: Este archivo contiene las variables globales del juego '''

from pygame import FULLSCREEN, SCALED

# SCREEN SETTINGS
RESOLUTION = ANCHO, ALTO = 1920 / 2 , 1080 / 2 # 960 x 540
FLAGS = SCALED
FPS = 60

# PLAYER SETTING
X = ANCHO / 2 - 50 # 430
Y = ALTO - 96 # 444
PLAYER_SPEED = 0.4
PLAYER_LIFE = 4

# NPC SETTING
NPC_LIFE = 1
NPC_SPEED = 0.10
NPC_INTERVAL = 5000

# ASTEROID SETTING
ASTEROID_SPEED = 0.20
ASTEROID_INTERVAL = 1000
ASTEROID_LIFE = 5

# BACKGROUND SETTING
BACKGROUND_SPEED = 0.05

# BULLET SETTING
BULLET_SPEED = 0.75
BULLET_DAMAGE = 1
