import pygame as pg

# SCREEN SETTINGS
RESOLUTION = ANCHO, ALTO = 1920 / 2 , 1080 / 2
FLAGS = pg.FULLSCREEN | pg.SCALED
FPS = 60

# PLAYERE SETTING 
X = (ANCHO / 2)
Y = (9 * ALTO / 10)
PLAYER_SPEED = 0.5
LIFE = 5

# ASTEROID SETTING
MAX_ASTEROIDS = 10